### ISSUE TITLE
[bug, feat] cannot create a delivery partner

### ISSUE THREAD

**Issue by opxdelwin** [tech-mySanji/branch_manager_app_archive#1]
As of now, a new delivery partner needs to be manually created. To overcome this, add appropriate feature in branch manager app. Also use appropriate security rules to verify incoming requests.

**Comment by abinbabuabu** [comment]
There is no incoming request. Delivery partner is created manually and login details are shared to the delivery partner. Deletion of delivery partner should be there.

**Comment by opxdelwin** [comment]
By incoming request it was meant that CRUD request from branch manager application only...
