### ISSUE TITLE
[feat] view all users

### ISSUE THREAD

**Issue by opxdelwin** [tech-mySanji/branch_manager_app_archive#3]
The Branch manager can add, edit, delete or block a customers account, mobile number or email id.
Can view all customers that is mapped to the branch.

![image](https://github.com/tech-mySanji/branch_manager_app_archive/assets/84124091/1b9d3dab-a790-4252-b417-d2e069e58985)

**Comment by MySanji** [comment]
can edit the location pin and address entered as well

**Comment by opxdelwin** [comment]
So location pin and address would be separate? I don't think we support getting `LatLng` from addresses right now, it'd need to be entered manually.

For sure we get an approximate location of the  device using GPS, but exacts would be entered by the user, and delivery rep and update both.
