### ISSUE TITLE
Unknown error in adding delivery agent

### ISSUE THREAD

**Issue by KenJose03** [tech-mySanji/branch_manager_app_archive#36]
https://github.com/tech-mySanji/branch_manager_app_archive/assets/88197456/6411ed59-fba2-4059-b607-52c5f0c6068c

**Comment by opxdelwin** [comment]
Can you confirm with the phone number being exactly 10 digits? it's probably that.

**Comment by opxdelwin** [comment]
Can you check if the issue persists even when the agent's phone number is 10 digits?

It'd be better to put a number check into the code as well.
